# Generated by Django 4.1.7 on 2023-04-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='project_name',
        ),
    ]
