# Generated by Django 4.1.7 on 2023-04-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0002_rename_content_post_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='project_name',
            new_name='content',
        ),
    ]
