# Generated by Django 4.1.7 on 2023-04-02 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpals', '0004_delete_embedded_post_image_post_name_post_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='embedded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('project', models.CharField(default='', max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='projectpals/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
