# Generated by Django 4.1.7 on 2023-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0005_embedded_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embedded',
            old_name='name',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='embedded',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='embedded',
            old_name='project',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='embedded',
            name='year',
            field=models.CharField(choices=[('FR', '1st'), ('SO', '2nd'), ('JR', '3rd'), ('SR', '4th')], default='FR', max_length=2),
        ),
    ]
