# Generated by Django 4.1.7 on 2023-04-02 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectpals', '0006_rename_name_embedded_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=20)),
                ('year', models.CharField(choices=[('FR', '1st'), ('SO', '2nd'), ('JR', '3rd'), ('SR', '4th')], default='FR', max_length=2)),
                ('project_name', models.CharField(default='', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='projectpals/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
