# Generated by Django 4.2 on 2023-04-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0009_post_users_alter_category_name_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
