# Generated by Django 4.2 on 2023-04-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0010_remove_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users',
            new_name='user',
        ),
    ]
