# Generated by Django 4.2 on 2023-04-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpals', '0011_rename_users_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
